### ISSUE TITLE
File extention is missing

### ISSUE THREAD

**Issue by fibonatic** [aslushnikov/latex-online#40] opened 2018-01-13 10:13 UTC
The file I downloaded after compiling did not have any file extension (using: http://latex.aslushnikov.com/compile?git=git://github.com/RoboCupAtHome/RuleBook.git&target=Rulebook.tex). After I manually added the extension *.pdf I was able to open the file and did get the expected result.

**Comment by aslushnikov** [comment] 2021-05-23 09:51
I unfortunately can't reproduce in 2021 on Mac OS. I'll close this - please re-file if this is still relevant.

**Closed by aslushnikov** 2021-05-23 09:51 UTC
