### ISSUE TITLE
External PDF-viewer spawned periodically

### ISSUE THREAD

**Issue by Skillmon** [aslushnikov/latex-online#61] opened 2020-04-08 10:53 UTC
When embedding latexonline into a github page to compile LaTeX examples everything behaves well as long as the default built-in PDF viewer of Firefox is used.

When I configure Firefox to use an external PDF viewer that viewer gets spawned periodically. Confirmed this bug with FF version 74.0.1 on Arch Linux. Used external viewers were Evince and Zathura.

A gif of the buggy behaviour with Zathura as the external viewer:

![peek_2020-04-08_12-35](https://user-images.githubusercontent.com/8701017/78776266-da6fbd00-7997-11ea-9699-5b48e46ef863.gif)

**Comment by davidcarlisle** [comment] 2020-04-08 11:00
Currently it's using an `<iframe>` there are other possibilities using `<object>` or having it open in a new tab/windows,

If you want to experiment with code that works in your setup you can use a simple url such as

```
https://latexonline.cc/compile?text=%5Cdocumentclass%7Barticle%7D%5Cbegin%7Bdocument%7Dhello%5Cend%7Bdocument%7D
```

https://latexonline.cc/compile?text=%5Cdocumentclass%7Barticle%7D%5Cbegin%7Bdocument%7Dhello%5Cend%7Bdocument%7D

**Comment by davidcarlisle** [comment] 2020-04-08 11:06
This is probably an issue with the iframe embedding used on that site (which is just in initial pre-test phase currently) we could open in a new window or use object, if iframe turns out not to be suitable

**Comment by davidcarlisle** [comment] 2020-05-26 19:43
> 
> 
> This is probably an issue with the iframe embedding used on that site (which is just in initial pre-test phase currently) we could open in a new window or use object, if iframe turns out not to be suitable

My comment above is incorrect this can be reproduced without the learnlatex code by using the latexonline.cc example demo by first choosing (any) external pdf viewer in the firefox options menu. Firefox will then spawn dialog boxes repeatedly until the tab is killed.

**Comment by aslushnikov** [comment] 2021-05-23 08:45
This is fixed with https://github.com/aslushnikov/latex-online/commit/210189b2f69d355e5cbba011056e8cc8f9063485

**Closed by aslushnikov** 2021-05-23 08:45 UTC
